create database customer_behavior;

use customer_behavior;
select * from customer limit 10;

-- Q1. What is the total revenue generated by male vs female customer
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;


-- Q2. Which customer used a discount but still spent more than the average purchase amount
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
        SELECT AVG(purchase_amount)
        FROM customer
      );

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS Average_Rating
FROM customer
GROUP BY item_purchased
ORDER BY Average_Rating DESC
LIMIT 5;


-- Q4. Compare the average purchase amount between standard and express shipping
select shipping_type, round(avg(purchase_amount), 2) as AveragePrice
from customer
where shipping_type in ('Express', 'Standard')
group by shipping_type;


-- Q5. Do subscribed cusomers spend more? compare average spend and total revenue subs and non-subsribes.
SELECT 
    subscription_status,
    count(customer_id) as total_customers,
    ROUND(AVG(purchase_amount), 2) AS AveragePrice,
    ROUND(SUM(purchase_amount), 2) AS Total
FROM customer
GROUP BY subscription_status
order by Total, AveragePrice desc;

-- Q6. Which 5 products have the highest percentage of purchase with discount applied
SELECT
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
        / COUNT(*) * 100,
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customer into new, returning and loyal based on their total number of previous purchases and show the count of each segment
with customer_type as (
	select customer_id, previous_purchases,
		CASE
			when previous_purchases = 1 then "New"
            when previous_purchases between 2 and 10 then "Returning"
            else "Loyal"
		end as customer_segment
	from customer
)
select customer_segment, count(*) as NumberOfCustomers
from customer_type
group by customer_segment;        


-- Q8. What are the top most 3 purchased product within each category
WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM product_counts
WHERE rn <= 3
ORDER BY category, purchase_count DESC;


-- Q9. Are cusomers who are repeat buyers (more than 5 previous purchase ) also likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer 
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group
select 
	age_group,
    sum(purchase_amount) as TotalRevenue
from customer 
group by age_group;
